server:
  port: 9001

spring:
  application:
    name: my-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: service
          uri: lb://SERVICE
          predicates:
            - Path=/service/**
            - Weight=group1, 9
          filters:
            - StripPrefix=1
        - id: service1
          uri: https://www.baidu.com
          predicates:
            - Path=/service/**
            - Weight=group1, 1
          filters:
            - StripPrefix=1



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}

